/**
 * YouTube subtitle fetching service
 * Multiple methods to extract subtitles from YouTube videos
 */

interface SubtitleTrack {
  language: string;
  languageCode: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  url: string;
}

interface SubtitleResult {
  success: boolean;
  text: string;
  error?: string;
  method?: string;
  logs?: string[];
}

const NETWORK_TIMEOUT_MS = 20000;

function formatErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }

  if (typeof error === 'string') {
    return error;
  }

  return 'Unknown error';
}

async function fetchFromPythonTranscriptApi(
  videoUrlOrId: string,
  langCode: string,
  logs: string[]
): Promise<SubtitleResult> {
  logs.push(`Python helper: requesting transcript for language "${langCode}"`)

  try {
    const response = await fetch(
      `/api/youtube-transcript?url=${encodeURIComponent(videoUrlOrId)}&lang=${encodeURIComponent(langCode)}`,
      {
        signal: AbortSignal.timeout(60000),
      }
    );

    const data = (await response.json()) as SubtitleResult;
    logs.push(
      `Python helper: HTTP ${response.status}${data.error ? `, message: ${data.error}` : ''}`
    )

    return {
      success: Boolean(data.success && data.text?.trim()),
      text: data.text || '',
      error: data.error,
      method: data.method || 'yt-dlp',
      logs,
    };
  } catch (err) {
    const message = formatErrorMessage(err);
    logs.push(`Python helper failed: ${message}`)
    console.warn('Python transcript API failed:', err);
    return {
      success: false,
      text: '',
      error: 'Local Python transcript service is unavailable.',
      logs,
    };
  }
}

function toAllOriginsRaw(url: string): string {
  return `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`;
}

function toCorsProxyIo(url: string): string {
  return `https://corsproxy.io/?${encodeURIComponent(url)}`;
}

function toCodeTabs(url: string): string {
  return `https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(url)}`;
}

async function fetchThroughProxies(
  label: string,
  targetUrl: string,
  logs: string[],
  timeoutMs = NETWORK_TIMEOUT_MS
): Promise<Response | null> {
  const candidates = [
    { name: 'AllOrigins', url: toAllOriginsRaw(targetUrl) },
    { name: 'corsproxy.io', url: toCorsProxyIo(targetUrl) },
    { name: 'CodeTabs', url: toCodeTabs(targetUrl) },
  ];

  for (const candidate of candidates) {
    try {
      logs.push(`${label}: requesting via ${candidate.name}`);
      const response = await fetch(candidate.url, {
        signal: AbortSignal.timeout(timeoutMs),
      });
      logs.push(`${label}: ${candidate.name} HTTP ${response.status}`);
      if (response.ok) {
        return response;
      }
    } catch (err) {
      logs.push(`${label}: ${candidate.name} failed: ${formatErrorMessage(err)}`);
    }
  }

  return null;
}

/**
 * Parse XML subtitle format (YouTube timedtext)
 */
export function parseYouTubeXML(xmlText: string): string {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(xmlText, 'text/xml');

    // Check for parse errors
    const parseError = doc.querySelector('parsererror');
    if (parseError) {
      return '';
    }

    const textElements = doc.querySelectorAll('text');
    const texts: string[] = [];

    textElements.forEach((el) => {
      const text = el.textContent?.trim();
      if (text) {
        // Remove HTML tags and clean up
        const cleaned = text
          .replace(/<[^>]*>/g, '')
          .replace(/\n/g, ' ')
          .replace(/\s+/g, ' ')
          .trim();

        if (cleaned) {
          texts.push(cleaned);
        }
      }
    });

    return texts.join(' ');
  } catch (err) {
    console.error('Error parsing XML:', err);
    return '';
  }
}

/**
 * Parse SRT format subtitles
 */
export function parseSRT(srtText: string): string {
  const lines = srtText.split(/\r?\n/);
  const textLines: string[] = [];

  for (const line of lines) {
    // Skip sequence numbers and timestamps
    if (/^\d+$/.test(line.trim()) || /^\d{2}:\d{2}:\d{2}/.test(line.trim())) {
      continue;
    }
    // Skip empty lines
    if (line.trim() === '') continue;

    // Clean up HTML tags and special characters
    let cleaned = line
      .replace(/<[^>]*>/g, '')
      .replace(/\{[^}]*\}/g, '')
      .replace(/&[^;]+;/g, ' ')
      .trim();

    if (cleaned) {
      textLines.push(cleaned);
    }
  }

  return textLines.join(' ');
}

/**
 * Parse VTT format subtitles
 */
export function parseVTT(vttText: string): string {
  const lines = vttText.split(/\r?\n/);
  const textLines: string[] = [];
  let skipHeader = true;

  for (const line of lines) {
    if (skipHeader) {
      if (line.includes('WEBVTT')) continue;
      if (line.trim() === '') {
        skipHeader = false;
        continue;
      }
      continue;
    }

    // Skip timestamps
    if (line.includes('-->')) continue;
    if (/^\d{2}:\d{2}:\d{2}/.test(line.trim())) continue;
    if (line.trim() === '') continue;

    let cleaned = line.replace(/<[^>]*>/g, '').trim();

    if (cleaned) {
      textLines.push(cleaned);
    }
  }

  return textLines.join(' ');
}

/**
 * Auto-detect subtitle format and parse
 */
export function parseSubtitles(text: string, format?: 'srt' | 'vtt' | 'xml'): string {
  if (format === 'srt') return parseSRT(text);
  if (format === 'vtt') return parseVTT(text);
  if (format === 'xml') return parseYouTubeXML(text);

  // Auto-detect
  if (text.includes('WEBVTT')) return parseVTT(text);
  if (text.includes('<?xml') || text.includes('<timedtext')) return parseYouTubeXML(text);
  if (/^\d+\r?\n\d{2}:\d{2}:\d{2}/.test(text)) return parseSRT(text);

  // Assume plain text
  return text.replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').trim();
}

function decodeHtmlEntities(text: string): string {
  const textarea = document.createElement('textarea');
  textarea.innerHTML = text;
  return textarea.value;
}

function normalizeSubtitleText(text: string): string {
  return decodeHtmlEntities(text)
    .replace(/\u00a0/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Extract video ID from YouTube URL
 */
export function extractYouTubeVideoId(url: string): string | null {
  const trimmed = url.trim();

  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed;
  }

  try {
    const parsed = new URL(trimmed);
    const hostname = parsed.hostname.replace(/^www\./, '').replace(/^m\./, '');

    if (hostname === 'youtu.be') {
      const id = parsed.pathname.split('/').filter(Boolean)[0];
      return id && /^[a-zA-Z0-9_-]{11}$/.test(id) ? id : null;
    }

    if (
      hostname === 'youtube.com' ||
      hostname === 'music.youtube.com' ||
      hostname === 'youtube-nocookie.com'
    ) {
      const directId = parsed.searchParams.get('v');
      if (directId && /^[a-zA-Z0-9_-]{11}$/.test(directId)) {
        return directId;
      }

      const segments = parsed.pathname.split('/').filter(Boolean);
      const candidate = segments.find((segment, index) =>
        ['embed', 'shorts', 'live', 'v'].includes(segments[index - 1] || '')
      );

      if (candidate && /^[a-zA-Z0-9_-]{11}$/.test(candidate)) {
        return candidate;
      }
    }
  } catch {
    // Fall back to regex parsing for partially formed URLs.
  }

  const patterns = [
    /(?:youtube\.com\/watch\?.*v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/i,
    /youtube\.com\/shorts\/([a-zA-Z0-9_-]{11})/i,
    /youtube\.com\/live\/([a-zA-Z0-9_-]{11})/i,
    /youtube\.com\/v\/([a-zA-Z0-9_-]{11})/i,
  ];

  for (const pattern of patterns) {
    const match = trimmed.match(pattern);
    if (match) {
      return match[1];
    }
  }

  return null;
}

function safeJsonParse<T>(value: string): T | null {
  try {
    return JSON.parse(value) as T;
  } catch {
    return null;
  }
}

function extractJsonObject(source: string, startIndex: number): string | null {
  let depth = 0;
  let inString = false;
  let isEscaped = false;
  let started = false;

  for (let index = startIndex; index < source.length; index++) {
    const char = source[index];

    if (!started) {
      if (char === '{') {
        started = true;
        depth = 1;
      }
      continue;
    }

    if (inString) {
      if (isEscaped) {
        isEscaped = false;
        continue;
      }

      if (char === '\\') {
        isEscaped = true;
        continue;
      }

      if (char === '"') {
        inString = false;
      }

      continue;
    }

    if (char === '"') {
      inString = true;
      continue;
    }

    if (char === '{') {
      depth++;
      continue;
    }

    if (char === '}') {
      depth--;

      if (depth === 0) {
        return source.slice(startIndex, index + 1);
      }
    }
  }

  return null;
}

function extractInitialPlayerResponse(html: string): Record<string, unknown> | null {
  const markers = ['ytInitialPlayerResponse = ', 'var ytInitialPlayerResponse = '];

  for (const marker of markers) {
    const markerIndex = html.indexOf(marker);
    if (markerIndex === -1) {
      continue;
    }

    const jsonStart = html.indexOf('{', markerIndex + marker.length);
    if (jsonStart === -1) {
      continue;
    }

    const jsonText = extractJsonObject(html, jsonStart);
    if (!jsonText) {
      continue;
    }

    const parsed = safeJsonParse<Record<string, unknown>>(jsonText);
    if (parsed) {
      return parsed;
    }
  }

  return null;
}

function extractCaptionTracksFromHtml(html: string): SubtitleTrack[] {
  const playerResponse = extractInitialPlayerResponse(html);
  const captions = playerResponse?.captions as
    | { playerCaptionsTracklistRenderer?: { captionTracks?: Array<Record<string, unknown>> } }
    | undefined;
  const tracks = captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  if (!tracks.length) {
    return [];
  }

  return tracks
    .map((track) => {
      const baseUrl = typeof track.baseUrl === 'string' ? track.baseUrl : '';
      const languageCode = typeof track.languageCode === 'string' ? track.languageCode : '';
      const simpleText =
        typeof track.name === 'object' &&
        track.name &&
        'simpleText' in track.name &&
        typeof (track.name as { simpleText?: unknown }).simpleText === 'string'
          ? (track.name as { simpleText: string }).simpleText
          : languageCode;

      if (!baseUrl || !languageCode) {
        return null;
      }

      return {
        language: simpleText,
        languageCode,
        isAutoGenerated: baseUrl.includes('kind=asr'),
        isTranslatable: track.isTranslatable === true,
        url: baseUrl,
      };
    })
    .filter((track): track is SubtitleTrack => Boolean(track));
}

function chooseBestTrack(tracks: SubtitleTrack[], ytLang: string): SubtitleTrack | null {
  if (tracks.length === 0) {
    return null;
  }

  const normalizedTarget = ytLang.toLowerCase();
  const baseTarget = normalizedTarget.split('-')[0];

  const preferredTrack =
    tracks.find((track) => track.languageCode.toLowerCase() === normalizedTarget && !track.isAutoGenerated) ||
    tracks.find((track) => track.languageCode.toLowerCase().startsWith(baseTarget) && !track.isAutoGenerated) ||
    tracks.find((track) => track.languageCode.toLowerCase() === normalizedTarget) ||
    tracks.find((track) => track.languageCode.toLowerCase().startsWith(baseTarget)) ||
    tracks[0];

  return preferredTrack ?? null;
}

function buildTimedTextUrl(videoId: string, ytLang: string, autoGenerated = false): string {
  const url = new URL('https://www.youtube.com/api/timedtext');
  url.searchParams.set('v', videoId);
  url.searchParams.set('lang', ytLang);

  if (autoGenerated) {
    url.searchParams.set('kind', 'asr');
  }

  return url.toString();
}

function buildTrackFetchUrl(track: SubtitleTrack, ytLang: string): string {
  const url = new URL(track.url);
  url.searchParams.delete('fmt');

  const requestedLangBase = ytLang.toLowerCase().split('-')[0];
  const trackLangBase = track.languageCode.toLowerCase().split('-')[0];

  if (
    track.isTranslatable &&
    trackLangBase !== requestedLangBase &&
    !url.searchParams.has('tlang')
  ) {
    url.searchParams.set('tlang', ytLang);
  }

  return url.toString();
}

/**
 * Convert language code to YouTube format
 */
export function langToYouTubeCode(langCode: string): string {
  const code = langCode.split('-')[0];
  const map: Record<string, string> = {
    en: 'en',
    es: 'es',
    'es-ES': 'es',
    fr: 'fr',
    de: 'de',
    it: 'it',
    pt: 'pt',
    'pt-BR': 'pt',
    zh: 'zh-Hans',
    'zh-CN': 'zh-Hans',
    ja: 'ja',
    ko: 'ko',
    ar: 'ar',
    'ar-SA': 'ar',
    hi: 'hi',
    'hi-IN': 'hi',
    ru: 'ru',
    'ru-RU': 'ru',
  };
  return map[langCode] || map[code] || 'en';
}

/**
 * Fetch subtitles using multiple methods with fallbacks
 */
export async function fetchYouTubeSubtitles(
  videoId: string,
  langCode: string
): Promise<SubtitleResult> {
  const ytLang = langToYouTubeCode(langCode);
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const logs: string[] = [
    `Starting YouTube extraction for video "${videoId}"`,
    `Requested app language "${langCode}", mapped YouTube language "${ytLang}"`,
  ];

  // Method 0: Local Python youtube-transcript-api bridge
  const pythonResult = await fetchFromPythonTranscriptApi(watchUrl, ytLang, logs);
  if (pythonResult.success && pythonResult.text.trim()) {
    logs.push(
      `Success via ${pythonResult.method || 'youtube-transcript-api'} with ${pythonResult.text.length} characters`
    );
    return pythonResult;
  }
  logs.push(
    `Python helper did not return transcript${pythonResult.error ? `: ${pythonResult.error}` : ''}`
  );

  // Method 1: Try YouTube's timedtext API with CORS proxy
  try {
    const response = await fetchThroughProxies(
      'Timedtext',
      buildTimedTextUrl(videoId, ytLang),
      logs
    );

    if (response?.ok) {
      const xmlText = await response.text();
      const text = normalizeSubtitleText(parseYouTubeXML(xmlText));

      if (text.trim()) {
        logs.push(`Timedtext: parsed ${text.length} characters`);
        return {
          success: true,
          text,
          method: 'timedtext',
          logs,
        };
      }

      logs.push('Timedtext: response received but transcript text was empty');
    }
  } catch (err) {
    logs.push(`Timedtext failed: ${formatErrorMessage(err)}`);
    console.warn('Method 1 failed:', err);
  }

  // Method 2: Try fetching video page and extracting subtitle tracks
  try {
    const response = await fetchThroughProxies('Caption tracks from page', watchUrl, logs);

    if (response?.ok) {
      const html = await response.text();

      const captionTracks = extractCaptionTracksFromHtml(html);
      logs.push(`Caption tracks from page: found ${captionTracks.length} track(s)`);
      const selectedTrack = chooseBestTrack(captionTracks, ytLang);

      if (selectedTrack) {
        logs.push(
          `Caption tracks from page: selected ${selectedTrack.languageCode} (${selectedTrack.language})${
            selectedTrack.isAutoGenerated ? ', auto-generated' : ''
          }`
        );
        const subtitleUrl = buildTrackFetchUrl(selectedTrack, ytLang);

        const subtitleResponse = await fetch(
          toAllOriginsRaw(subtitleUrl),
          { signal: AbortSignal.timeout(NETWORK_TIMEOUT_MS) }
        );
        logs.push(`Caption tracks from page: subtitle track HTTP ${subtitleResponse.status}`);

        if (subtitleResponse.ok) {
          const subtitleText = await subtitleResponse.text();
          const text = normalizeSubtitleText(parseSubtitles(subtitleText));

          if (text.trim()) {
            logs.push(`Caption tracks from page: parsed ${text.length} characters`);
            return {
              success: true,
              text,
              method: selectedTrack.isAutoGenerated ? 'caption-tracks-auto' : 'caption-tracks',
              logs,
            };
          }

          logs.push('Caption tracks from page: subtitle payload received but parsed text was empty');
        }
      } else {
        logs.push('Caption tracks from page: no matching caption track was selected');
      }
    }
  } catch (err) {
    logs.push(`Caption tracks from page failed: ${formatErrorMessage(err)}`);
    console.warn('Method 2 failed:', err);
  }

  // Method 3: Try with auto-generated captions (a.en for English)
  try {
    const response = await fetchThroughProxies(
      'Auto-generated timedtext',
      buildTimedTextUrl(videoId, ytLang, true),
      logs
    );

    if (response?.ok) {
      const xmlText = await response.text();
      const text = normalizeSubtitleText(parseYouTubeXML(xmlText));

      if (text.trim()) {
        logs.push(`Auto-generated timedtext: parsed ${text.length} characters`);
        return {
          success: true,
          text,
          method: 'auto-generated',
          logs,
        };
      }

      logs.push('Auto-generated timedtext: response received but transcript text was empty');
    }
  } catch (err) {
    logs.push(`Auto-generated timedtext failed: ${formatErrorMessage(err)}`);
    console.warn('Method 3 failed:', err);
  }

  // Method 4: Dedicated subtitle API fallback
  try {
    logs.push('DownSub fallback: requesting dedicated subtitle API');
    const result = await fetchFromSubtitleApi(videoId);
    if (result.error) {
      logs.push(`DownSub fallback: ${result.error}`);
    }
    if (result.success && result.text.trim()) {
      logs.push(`DownSub fallback: parsed ${result.text.length} characters`);
      return result;
    }
  } catch (err) {
    logs.push(`DownSub fallback failed: ${formatErrorMessage(err)}`);
    console.warn('Method 4 failed:', err);
  }

  logs.push('All extraction methods failed');
  return {
    success: false,
    text: '',
    error:
      'Could not fetch subtitles. The video may not have subtitles available, or the service is temporarily unavailable. Try pasting subtitles manually.',
    logs,
  };
}

/**
 * Alternative: Use a dedicated subtitle API service
 */
export async function fetchFromSubtitleApi(videoId: string): Promise<SubtitleResult> {
  try {
    // Using DownSub API (free, no key required)
    const response = await fetch(
      `https://downsub.com/api/download?url=https://www.youtube.com/watch?v=${videoId}`,
      { signal: AbortSignal.timeout(NETWORK_TIMEOUT_MS) }
    );

    if (response.ok) {
      const data = await response.text();
      const text = normalizeSubtitleText(parseSubtitles(data));

      if (text.trim()) {
        return {
          success: true,
          text,
          method: 'downsub-api',
        };
      }
    }
  } catch (err) {
    console.warn('Subtitle API failed:', err);
  }

  return {
    success: false,
    text: '',
    error: 'Subtitle service unavailable',
  };
}
