// Language configuration with flags and speech recognition codes
export interface Language {
  code: string;
  name: string;
  flag: string;
  speechCode: string; // Web Speech API language code
  voiceCommands: Record<string, string>;
}

export const SUPPORTED_LANGUAGES: Record<string, Language> = {
  'en-US': {
    code: 'en-US',
    name: 'English (US)',
    flag: '🇺🇸',
    speechCode: 'en-US',
    voiceCommands: {
      'new paragraph': '\n\n',
      'new line': '\n',
      'period': '.',
      'comma': ',',
      'question mark': '?',
      'exclamation mark': '!',
      'colon': ':',
      'semicolon': ';',
      'open quote': '"',
      'close quote': '"',
      'open paren': '(',
      'close paren': ')',
      'stop': 'STOP_COMMAND',
      'pause': 'PAUSE_COMMAND',
      'resume': 'RESUME_COMMAND',
      'delete last word': 'DELETE_LAST_WORD',
      'delete all': 'DELETE_ALL',
      'copy text': 'COPY_TEXT',
      'save draft': 'SAVE_DRAFT',
    },
  },
  'en-GB': {
    code: 'en-GB',
    name: 'English (UK)',
    flag: '🇬🇧',
    speechCode: 'en-GB',
    voiceCommands: {
      'new paragraph': '\n\n',
      'new line': '\n',
      'full stop': '.',
      'comma': ',',
      'question mark': '?',
      'exclamation mark': '!',
      'stop': 'STOP_COMMAND',
      'pause': 'PAUSE_COMMAND',
      'resume': 'RESUME_COMMAND',
      'delete last word': 'DELETE_LAST_WORD',
      'delete all': 'DELETE_ALL',
    },
  },
  'en-AU': {
    code: 'en-AU',
    name: 'English (AU)',
    flag: '🇦🇺',
    speechCode: 'en-AU',
    voiceCommands: {
      'new paragraph': '\n\n',
      'new line': '\n',
      'period': '.',
      'comma': ',',
      'question mark': '?',
      'exclamation mark': '!',
      'stop': 'STOP_COMMAND',
      'pause': 'PAUSE_COMMAND',
      'resume': 'RESUME_COMMAND',
      'delete last word': 'DELETE_LAST_WORD',
      'delete all': 'DELETE_ALL',
    },
  },
  'es-ES': {
    code: 'es-ES',
    name: 'Español',
    flag: '🇪🇸',
    speechCode: 'es-ES',
    voiceCommands: {
      'nuevo párrafo': '\n\n',
      'nueva línea': '\n',
      'punto': '.',
      'coma': ',',
      'signo de pregunta': '?',
      'signo de exclamación': '!',
      'detener': 'STOP_COMMAND',
      'pausa': 'PAUSE_COMMAND',
      'continuar': 'RESUME_COMMAND',
      'borrar última palabra': 'DELETE_LAST_WORD',
      'borrar todo': 'DELETE_ALL',
    },
  },
  'fr-FR': {
    code: 'fr-FR',
    name: 'Français',
    flag: '🇫🇷',
    speechCode: 'fr-FR',
    voiceCommands: {
      'nouveau paragraphe': '\n\n',
      'nouvelle ligne': '\n',
      'point': '.',
      'virgule': ',',
      'point d\'interrogation': '?',
      'point d\'exclamation': '!',
      'stop': 'STOP_COMMAND',
      'pause': 'PAUSE_COMMAND',
      'reprendre': 'RESUME_COMMAND',
      'supprimer dernier mot': 'DELETE_LAST_WORD',
      'tout supprimer': 'DELETE_ALL',
    },
  },
  'de-DE': {
    code: 'de-DE',
    name: 'Deutsch',
    flag: '🇩🇪',
    speechCode: 'de-DE',
    voiceCommands: {
      'neuer absatz': '\n\n',
      'neue zeile': '\n',
      'punkt': '.',
      'komma': ',',
      'fragezeichen': '?',
      'ausrufezeichen': '!',
      'stopp': 'STOP_COMMAND',
      'pause': 'PAUSE_COMMAND',
      'fortsetzen': 'RESUME_COMMAND',
      'letztes wort löschen': 'DELETE_LAST_WORD',
      'alles löschen': 'DELETE_ALL',
    },
  },
  'it-IT': {
    code: 'it-IT',
    name: 'Italiano',
    flag: '🇮🇹',
    speechCode: 'it-IT',
    voiceCommands: {
      'nuovo paragrafo': '\n\n',
      'nuova riga': '\n',
      'punto': '.',
      'virgola': ',',
      'punto interrogativo': '?',
      'punto esclamativo': '!',
      'stop': 'STOP_COMMAND',
      'pausa': 'PAUSE_COMMAND',
      'riprendi': 'RESUME_COMMAND',
      'cancella ultima parola': 'DELETE_LAST_WORD',
      'cancella tutto': 'DELETE_ALL',
    },
  },
  'pt-BR': {
    code: 'pt-BR',
    name: 'Português (BR)',
    flag: '🇧🇷',
    speechCode: 'pt-BR',
    voiceCommands: {
      'novo parágrafo': '\n\n',
      'nova linha': '\n',
      'ponto': '.',
      'vírgula': ',',
      'ponto de interrogação': '?',
      'ponto de exclamação': '!',
      'parar': 'STOP_COMMAND',
      'pausa': 'PAUSE_COMMAND',
      'continuar': 'RESUME_COMMAND',
      'apagar última palavra': 'DELETE_LAST_WORD',
      'apagar tudo': 'DELETE_ALL',
    },
  },
  'zh-CN': {
    code: 'zh-CN',
    name: '中文 (普通话)',
    flag: '🇨🇳',
    speechCode: 'zh-CN',
    voiceCommands: {
      '新段落': '\n\n',
      '换行': '\n',
      '句号': '。',
      '逗号': '，',
      '问号': '？',
      '感叹号': '！',
      '停止': 'STOP_COMMAND',
      '暂停': 'PAUSE_COMMAND',
      '继续': 'RESUME_COMMAND',
      '删除最后一个词': 'DELETE_LAST_WORD',
      '删除全部': 'DELETE_ALL',
    },
  },
  'ja-JP': {
    code: 'ja-JP',
    name: '日本語',
    flag: '🇯🇵',
    speechCode: 'ja-JP',
    voiceCommands: {
      '改行': '\n\n',
      '新しい行': '\n',
      '句点': '。',
      '読点': '、',
      '疑問符': '？',
      '感嘆符': '！',
      '停止': 'STOP_COMMAND',
      '一時停止': 'PAUSE_COMMAND',
      '再開': 'RESUME_COMMAND',
      '最後の単語を削除': 'DELETE_LAST_WORD',
      'すべて削除': 'DELETE_ALL',
    },
  },
  'ko-KR': {
    code: 'ko-KR',
    name: '한국어',
    flag: '🇰🇷',
    speechCode: 'ko-KR',
    voiceCommands: {
      '새 문단': '\n\n',
      '새 줄': '\n',
      '마침표': '.',
      '쉼표': ',',
      '물음표': '?',
      '느낌표': '!',
      '정지': 'STOP_COMMAND',
      '일시정지': 'PAUSE_COMMAND',
      '계속': 'RESUME_COMMAND',
      '마지막 단어 삭제': 'DELETE_LAST_WORD',
      '모두 삭제': 'DELETE_ALL',
    },
  },
  'ar-SA': {
    code: 'ar-SA',
    name: 'العربية',
    flag: '🇸🇦',
    speechCode: 'ar-SA',
    voiceCommands: {
      'فقرة جديدة': '\n\n',
      'سطر جديد': '\n',
      'نقطة': '.',
      'فاصلة': ',',
      'علامة استفهام': '?',
      'علامة تعجب': '!',
      'توقف': 'STOP_COMMAND',
      'إيقاف مؤقت': 'PAUSE_COMMAND',
      'استئناف': 'RESUME_COMMAND',
      'حذف الكلمة الأخيرة': 'DELETE_LAST_WORD',
      'حذف الكل': 'DELETE_ALL',
    },
  },
  'hi-IN': {
    code: 'hi-IN',
    name: 'हिन्दी',
    flag: '🇮🇳',
    speechCode: 'hi-IN',
    voiceCommands: {
      'नया पैराग्राफ': '\n\n',
      'नई पंक्ति': '\n',
      'पूर्ण विराम': '.',
      'अल्पविराम': ',',
      'प्रश्नवाचक चिह्न': '?',
      'विस्मयादिबोधक चिह्न': '!',
      'रुको': 'STOP_COMMAND',
      'रोको': 'PAUSE_COMMAND',
      'जारी रखो': 'RESUME_COMMAND',
      'आखिरी शब्द हटाओ': 'DELETE_LAST_WORD',
      'सब हटाओ': 'DELETE_ALL',
    },
  },
  'ru-RU': {
    code: 'ru-RU',
    name: 'Русский',
    flag: '🇷🇺',
    speechCode: 'ru-RU',
    voiceCommands: {
      'новый абзац': '\n\n',
      'новая строка': '\n',
      'точка': '.',
      'запятая': ',',
      'вопросительный знак': '?',
      'восклицательный знак': '!',
      'стоп': 'STOP_COMMAND',
      'пауза': 'PAUSE_COMMAND',
      'продолжить': 'RESUME_COMMAND',
      'удалить последнее слово': 'DELETE_LAST_WORD',
      'удалить всё': 'DELETE_ALL',
    },
  },
};

// Translation target languages (simplified)
export const TRANSLATION_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸' },
  { code: 'fr', name: 'French', flag: '🇫🇷' },
  { code: 'de', name: 'German', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', flag: '🇮🇹' },
  { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺' },
];

// Helper to get language by code
export function getLanguage(code: string): Language | undefined {
  return SUPPORTED_LANGUAGES[code];
}

// Helper to get all languages as array
export function getLanguages(): Language[] {
  return Object.values(SUPPORTED_LANGUAGES);
}
